create table if not exists command_inbox (
  tenant_id varchar(120) not null,
  authenticated_producer_ref varchar(240) not null,
  command_id varchar(160) not null,
  payload_fingerprint char(64) not null,
  disposition varchar(40) not null,
  run_id varchar(160),
  first_topic varchar(240) not null,
  first_partition integer not null,
  first_offset bigint not null,
  primary key (tenant_id, authenticated_producer_ref, command_id)
);

create table if not exists admitted_work (
  tenant_id varchar(120) not null,
  authenticated_producer_ref varchar(240) not null,
  command_id varchar(160) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  correlation_id varchar(160) not null,
  primary key (tenant_id, authenticated_producer_ref, command_id),
  unique (run_id)
);

create table if not exists ingress_quarantine (
  id bigint generated by default as identity primary key,
  tenant_id varchar(120),
  authenticated_producer_ref varchar(240) not null,
  command_id varchar(160),
  received_fingerprint char(64) not null,
  reason varchar(120) not null,
  source_topic varchar(240) not null,
  source_partition integer not null,
  source_offset bigint not null
);

create table if not exists artifact_content (
  tenant_id varchar(120) not null,
  artifact_id varchar(160) not null,
  source_reference varchar(600) not null,
  source_system varchar(160) not null,
  source_version varchar(160) not null,
  observed_at timestamp with time zone not null,
  retrieved_at timestamp with time zone not null,
  valid_until timestamp with time zone not null,
  content_type varchar(160) not null,
  trust_class varchar(60) not null,
  source_size_bytes integer not null,
  source_sha256 char(64) not null,
  source_bytes bytea not null,
  primary key (tenant_id, artifact_id),
  unique (tenant_id, source_system, source_reference, source_version)
);

create table if not exists artifact_view (
  tenant_id varchar(120) not null,
  view_id varchar(160) not null,
  artifact_id varchar(160) not null,
  normalization_version varchar(160) not null,
  redaction_policy_version varchar(160) not null,
  view_size_bytes integer not null,
  view_sha256 char(64) not null,
  model_safe_text text not null,
  primary key (tenant_id, view_id),
  foreign key (tenant_id, artifact_id)
    references artifact_content (tenant_id, artifact_id)
);

create table if not exists context_snapshot (
  tenant_id varchar(120) not null,
  snapshot_id varchar(160) not null,
  run_id varchar(160) not null,
  command_id varchar(160) not null,
  admitted_work_fingerprint char(64) not null,
  instruction_set_ref varchar(200) not null,
  policy_set_ref varchar(200) not null,
  capability_catalog_ref varchar(200) not null,
  created_at timestamp with time zone not null,
  selection_policy_version varchar(160) not null,
  token_estimator_version varchar(160) not null,
  max_context_bytes integer not null,
  max_estimated_tokens integer not null,
  used_context_bytes integer not null,
  estimated_tokens integer not null,
  primary key (tenant_id, snapshot_id),
  unique (tenant_id, run_id)
);

create table if not exists context_snapshot_item (
  tenant_id varchar(120) not null,
  snapshot_id varchar(160) not null,
  item_ordinal integer not null,
  artifact_id varchar(160) not null,
  view_id varchar(160) not null,
  observed_at timestamp with time zone not null,
  retrieved_at timestamp with time zone not null,
  valid_until timestamp with time zone not null,
  content_type varchar(160) not null,
  trust_class varchar(60) not null,
  primary key (tenant_id, snapshot_id, item_ordinal),
  foreign key (tenant_id, snapshot_id)
    references context_snapshot (tenant_id, snapshot_id),
  foreign key (tenant_id, artifact_id)
    references artifact_content (tenant_id, artifact_id),
  foreign key (tenant_id, view_id)
    references artifact_view (tenant_id, view_id)
);

-- tag::investigation-run-schema[]
create table if not exists investigation_run (
  tenant_id varchar(120) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  correlation_id varchar(160) not null,
  command_id varchar(160) not null,
  plan_version varchar(160) not null,
  state varchar(60) not null,
  resume_state varchar(60),
  completion_decision varchar(80) not null,
  deadline_at timestamp with time zone not null,
  next_wake_at timestamp with time zone,
  attempt_count integer not null,
  evidence_set_ref varchar(600),
  evidence_set_sha256 char(64),
  version bigint not null,
  lease_owner varchar(200),
  lease_until timestamp with time zone,
  fence_token bigint not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, run_id)
);
-- end::investigation-run-schema[]

create table if not exists investigation_expected_work (
  tenant_id varchar(120) not null,
  run_id varchar(160) not null,
  work_name varchar(160) not null,
  required_work boolean not null,
  work_status varchar(40) not null,
  primary key (tenant_id, run_id, work_name),
  foreign key (tenant_id, run_id)
    references investigation_run (tenant_id, run_id)
);

create table if not exists process_message_inbox (
  tenant_id varchar(120) not null,
  message_id varchar(160) not null,
  run_id varchar(160) not null,
  payload_fingerprint char(64) not null,
  disposition varchar(60) not null,
  first_received_at timestamp with time zone not null,
  primary key (tenant_id, message_id)
);

create table if not exists process_message_rejection (
  rejection_id bigint generated by default as identity primary key,
  tenant_id varchar(120) not null,
  message_id varchar(160) not null,
  run_id varchar(160) not null,
  payload_fingerprint char(64) not null,
  reason varchar(80) not null,
  rejected_at timestamp with time zone not null
);

create table if not exists process_outbox (
  event_id varchar(160) not null primary key,
  tenant_id varchar(120) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  aggregate_version bigint not null,
  event_type varchar(120) not null,
  event_payload text not null,
  created_at timestamp with time zone not null,
  published_at timestamp with time zone,
  foreign key (tenant_id, run_id)
    references investigation_run (tenant_id, run_id)
);

-- tag::effect-ledger-schema[]
create table if not exists effect_ledger (
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  decision_ref varchar(600) not null,
  policy_snapshot_ref varchar(600) not null,
  effect_type varchar(80) not null,
  target_system varchar(160) not null,
  target_resource_key varchar(320) not null,
  warehouse_id varchar(160) not null,
  sku varchar(160) not null,
  quantity integer not null,
  order_id varchar(160),
  expected_order_version bigint,
  reservation_reference varchar(600),
  intent_sha256 char(64) not null,
  target_contract_ref varchar(240) not null,
  target_idempotency_key varchar(160) not null,
  idempotency_expires_at timestamp with time zone,
  effect_state varchar(60) not null,
  version bigint not null,
  attempt_count integer not null,
  lease_owner varchar(200),
  lease_until timestamp with time zone,
  fence_token bigint not null,
  target_reference varchar(600),
  resolution_evidence_ref varchar(600),
  caused_by_effect_id varchar(160),
  compensates_effect_id varchar(160),
  authority_ref varchar(600),
  authority_valid_until timestamp with time zone,
  authority_evidence_sha256 char(64),
  authority_configuration_ref varchar(240),
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, effect_id),
  unique (tenant_id, target_idempotency_key),
  foreign key (tenant_id, run_id)
    references investigation_run (tenant_id, run_id)
);
-- end::effect-ledger-schema[]

create table if not exists effect_attempt (
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  attempt_number integer not null,
  attempt_id varchar(200) not null,
  lease_owner varchar(200) not null,
  fence_token bigint not null,
  attempt_state varchar(60) not null,
  started_at timestamp with time zone not null,
  lease_until timestamp with time zone not null,
  finished_at timestamp with time zone,
  reason_code varchar(120),
  evidence_ref varchar(600),
  target_reference varchar(600),
  primary key (tenant_id, effect_id, attempt_number),
  unique (tenant_id, attempt_id),
  foreign key (tenant_id, effect_id)
    references effect_ledger (tenant_id, effect_id)
);

create table if not exists effect_reconciliation_observation (
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  observation_id varchar(200) not null,
  observation_sha256 char(64) not null,
  observed_outcome varchar(60) not null,
  target_reference varchar(600),
  evidence_ref varchar(600) not null,
  observed_at timestamp with time zone not null,
  primary key (tenant_id, effect_id, observation_id),
  foreign key (tenant_id, effect_id)
    references effect_ledger (tenant_id, effect_id)
);

create table if not exists effect_identity_collision (
  collision_id bigint generated by default as identity primary key,
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  existing_sha256 char(64) not null,
  received_sha256 char(64) not null,
  observed_at timestamp with time zone not null
);

create table if not exists effect_outbox (
  event_id varchar(240) not null primary key,
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  effect_version bigint not null,
  event_type varchar(120) not null,
  event_payload text not null,
  created_at timestamp with time zone not null,
  published_at timestamp with time zone,
  foreign key (tenant_id, effect_id)
    references effect_ledger (tenant_id, effect_id)
);

-- tag::approval-schema[]
create table if not exists approval_request (
  tenant_id varchar(120) not null,
  request_id varchar(160) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  proposal_event_id varchar(160) not null,
  proposal_id varchar(160) not null,
  effect_id varchar(160) not null,
  subject_sha256 char(64) not null,
  subject_payload text not null,
  proposer_ref varchar(240) not null,
  policy_decision_id varchar(160) not null,
  policy_ref varchar(240) not null,
  policy_disposition varchar(40) not null,
  required_role varchar(120) not null,
  required_approvals integer not null,
  approval_state varchar(60) not null,
  decision_due_at timestamp with time zone not null,
  authority_valid_until timestamp with time zone not null,
  version bigint not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, request_id),
  unique (tenant_id, proposal_id, effect_id)
);

create table if not exists approval_decision (
  tenant_id varchar(120) not null,
  decision_id varchar(160) not null,
  request_id varchar(160) not null,
  actor_ref varchar(240) not null,
  action varchar(40) not null,
  reason_code varchar(120) not null,
  request_version bigint not null,
  decided_at timestamp with time zone not null,
  primary key (tenant_id, decision_id),
  foreign key (tenant_id, request_id)
    references approval_request (tenant_id, request_id)
);

create table if not exists approval_message_inbox (
  tenant_id varchar(120) not null,
  decision_id varchar(160) not null,
  request_id varchar(160) not null,
  payload_fingerprint char(64) not null,
  disposition varchar(60) not null,
  received_at timestamp with time zone not null,
  primary key (tenant_id, decision_id)
);

create table if not exists approval_identity_collision (
  collision_id bigint generated by default as identity primary key,
  tenant_id varchar(120) not null,
  decision_id varchar(160) not null,
  existing_sha256 char(64) not null,
  received_sha256 char(64) not null,
  observed_at timestamp with time zone not null
);

create table if not exists approval_outbox (
  event_id varchar(200) not null primary key,
  tenant_id varchar(120) not null,
  request_id varchar(160) not null,
  case_id varchar(160) not null,
  approval_version bigint not null,
  event_type varchar(120) not null,
  event_payload text not null,
  created_at timestamp with time zone not null,
  published_at timestamp with time zone,
  foreign key (tenant_id, request_id)
    references approval_request (tenant_id, request_id)
);

create table if not exists authorized_effect (
  tenant_id varchar(120) not null,
  effect_id varchar(160) not null,
  request_id varchar(160) not null,
  approval_version bigint not null,
  subject_sha256 char(64) not null,
  authority_ref varchar(600) not null,
  recorded_at timestamp with time zone not null,
  primary key (tenant_id, effect_id),
  foreign key (tenant_id, request_id)
    references approval_request (tenant_id, request_id),
  foreign key (tenant_id, effect_id)
    references effect_ledger (tenant_id, effect_id)
);
-- end::approval-schema[]

-- tag::resolution-recovery-schema[]
create table if not exists resolution_plan (
  tenant_id varchar(120) not null,
  plan_id varchar(160) not null,
  run_id varchar(160) not null,
  case_id varchar(160) not null,
  proposal_id varchar(160) not null,
  plan_state varchar(60) not null,
  recovery_owner varchar(240) not null,
  deadline_at timestamp with time zone not null,
  evidence_set_ref varchar(600) not null,
  evidence_sha256 char(64) not null,
  configuration_ref varchar(240) not null,
  definition_sha256 char(64) not null,
  next_event_number bigint not null,
  last_event_id varchar(240) not null,
  version bigint not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, plan_id),
  foreign key (tenant_id, run_id)
    references investigation_run (tenant_id, run_id)
);

create table if not exists resolution_plan_effect (
  tenant_id varchar(120) not null,
  plan_id varchar(160) not null,
  step_number integer not null,
  effect_id varchar(160) not null,
  effect_role varchar(40) not null,
  effect_type varchar(80) not null,
  caused_by_effect_id varchar(160),
  compensates_effect_id varchar(160),
  target_contract_ref varchar(240) not null,
  authority_ref varchar(600) not null,
  authority_valid_until timestamp with time zone not null,
  evidence_sha256 char(64) not null,
  configuration_ref varchar(240) not null,
  reversibility varchar(40) not null,
  observed_state varchar(60) not null,
  observed_effect_version bigint not null,
  observation_evidence_ref varchar(600),
  primary key (tenant_id, plan_id, effect_id),
  unique (tenant_id, effect_id),
  foreign key (tenant_id, plan_id)
    references resolution_plan (tenant_id, plan_id),
  foreign key (tenant_id, effect_id)
    references effect_ledger (tenant_id, effect_id)
);

create table if not exists resolution_message_inbox (
  tenant_id varchar(120) not null,
  message_id varchar(160) not null,
  plan_id varchar(160) not null,
  payload_sha256 char(64) not null,
  disposition varchar(60) not null,
  received_at timestamp with time zone not null,
  primary key (tenant_id, message_id)
);

create table if not exists resolution_outbox (
  event_id varchar(240) not null primary key,
  tenant_id varchar(120) not null,
  plan_id varchar(160) not null,
  plan_version bigint not null,
  event_type varchar(120) not null,
  event_payload text not null,
  created_at timestamp with time zone not null,
  published_at timestamp with time zone,
  foreign key (tenant_id, plan_id)
    references resolution_plan (tenant_id, plan_id)
);
-- end::resolution-recovery-schema[]

-- tag::retry-schedule-schema[]
create table if not exists retry_schedule (
  tenant_id varchar(120) not null,
  schedule_id varchar(160) not null,
  run_id varchar(160) not null,
  operation_key varchar(240) not null,
  request_sha256 char(64) not null,
  failure_observation_id varchar(160) not null,
  reason_code varchar(120) not null,
  effect_id varchar(160),
  effect_state varchar(60),
  deadline_at timestamp with time zone not null,
  not_before timestamp with time zone not null,
  idempotency_expires_at timestamp with time zone,
  minimum_execution_millis bigint not null,
  configured_attempt_timeout_millis bigint not null,
  settlement_reserve_millis bigint not null,
  attempt_timeout_millis bigint not null,
  max_attempts integer not null,
  attempts_used integer not null,
  max_tokens bigint not null,
  tokens_used bigint not null,
  reserved_tokens bigint not null,
  max_cost_micros bigint not null,
  cost_used_micros bigint not null,
  reserved_cost_micros bigint not null,
  schedule_state varchar(40) not null,
  version bigint not null,
  claim_owner varchar(200),
  claim_until timestamp with time zone,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, schedule_id)
);
-- end::retry-schedule-schema[]

-- tag::route-security-decision-schema[]
create table if not exists route_security_decision (
  decision_id varchar(160) not null primary key,
  message_id varchar(160) not null,
  message_sha256 char(64),
  tenant_id varchar(120) not null,
  authenticated_workload_ref varchar(240) not null,
  service_ref varchar(240) not null,
  actor_ref varchar(240),
  action_name varchar(80) not null,
  resource_ref varchar(600) not null,
  producer_provenance_ref varchar(600) not null,
  producer_claim_sha256 char(64),
  tenant_claim_sha256 char(64),
  resource_claim_sha256 char(64),
  subject_claim_sha256 char(64),
  delegation_claim_sha256 char(64),
  audience varchar(240) not null,
  policy_ref varchar(240) not null,
  policy_sha256 char(64) not null,
  outcome varchar(20) not null,
  reason_code varchar(120) not null,
  invalid_field_code varchar(120),
  break_glass_grant_ref varchar(240),
  decided_at timestamp with time zone not null,
  context_expires_at timestamp with time zone not null
);

create table if not exists route_security_quarantine (
  decision_id varchar(160) not null primary key,
  tenant_id varchar(120) not null,
  message_sha256 char(64),
  reason_code varchar(120) not null,
  quarantine_state varchar(80) not null,
  recorded_at timestamp with time zone not null,
  foreign key (decision_id) references route_security_decision (decision_id)
);
-- end::route-security-decision-schema[]

-- tag::remote-peer-task-schema[]
create table if not exists remote_peer_task (
  tenant_id varchar(120) not null,
  remote_work_id varchar(160) not null,
  case_id varchar(160) not null,
  correlation_id varchar(160) not null,
  local_owner_ref varchar(240) not null,
  peer_ref varchar(240) not null,
  peer_task_id varchar(240),
  capability varchar(160) not null,
  protocol_family varchar(80) not null,
  protocol_version varchar(40) not null,
  interaction_profile varchar(160) not null,
  fixed_adapter_ref varchar(240) not null,
  registration_revision bigint not null,
  advertisement_sha256 char(64) not null,
  objective varchar(1000) not null,
  required_deliverables varchar(1000) not null,
  input_artifact_ref varchar(600) not null,
  input_artifact_sha256 char(64) not null,
  result_schema_ref varchar(600) not null,
  deadline_at timestamp with time zone not null,
  max_reported_tokens bigint not null,
  max_reported_cost_micros bigint not null,
  max_artifact_bytes integer not null,
  reported_tokens bigint not null,
  reported_cost_micros bigint not null,
  task_state varchar(60) not null,
  cancellation_reason varchar(120),
  containment_reason varchar(120),
  version bigint not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, remote_work_id),
  unique (tenant_id, peer_ref, peer_task_id)
);

create table if not exists remote_peer_message_inbox (
  tenant_id varchar(120) not null,
  message_id varchar(160) not null,
  remote_work_id varchar(160) not null,
  payload_sha256 char(64) not null,
  authenticated_peer_ref varchar(240) not null,
  disposition varchar(80) not null,
  received_at timestamp with time zone not null,
  primary key (tenant_id, message_id),
  foreign key (tenant_id, remote_work_id)
    references remote_peer_task (tenant_id, remote_work_id)
);

create table if not exists remote_peer_artifact (
  tenant_id varchar(120) not null,
  remote_work_id varchar(160) not null,
  artifact_id varchar(160) not null,
  artifact_ref varchar(600) not null,
  artifact_sha256 char(64) not null,
  artifact_size_bytes integer not null,
  result_schema_ref varchar(600) not null,
  provenance_ref varchar(600) not null,
  evidence_observed_at timestamp with time zone not null,
  evidence_valid_until timestamp with time zone not null,
  artifact_role varchar(20) not null,
  missing_deliverables varchar(600),
  received_at timestamp with time zone not null,
  primary key (tenant_id, remote_work_id, artifact_id),
  foreign key (tenant_id, remote_work_id)
    references remote_peer_task (tenant_id, remote_work_id)
);

create table if not exists remote_peer_outbox (
  event_id varchar(240) not null primary key,
  tenant_id varchar(120) not null,
  remote_work_id varchar(160) not null,
  task_version bigint not null,
  event_type varchar(120) not null,
  event_payload varchar(600) not null,
  created_at timestamp with time zone not null,
  published_at timestamp with time zone,
  foreign key (tenant_id, remote_work_id)
    references remote_peer_task (tenant_id, remote_work_id)
);
-- end::remote-peer-task-schema[]

-- tag::case-history-replay-schema[]
create table if not exists case_history_observation (
  tenant_id varchar(120) not null,
  observation_id varchar(160) not null,
  source_stream varchar(200) not null,
  source_sequence bigint not null,
  message_id varchar(160),
  event_id varchar(240),
  payload_sha256 char(64) not null,
  observation_sha256 char(64) not null,
  source_owner varchar(240) not null,
  event_class varchar(80) not null,
  outcome_code varchar(120) not null,
  trust_class varchar(80) not null,
  occurred_at timestamp with time zone not null,
  recorded_at timestamp with time zone not null,
  trace_id char(32),
  span_id char(16),
  usage_source varchar(40),
  usage_tokens bigint,
  usage_cost_micros bigint,
  measured_duration_millis bigint,
  measured_bytes bigint,
  summary_code varchar(160) not null,
  redaction_profile varchar(160) not null,
  retention_class varchar(80) not null,
  retain_until timestamp with time zone not null,
  primary key (tenant_id, observation_id)
);

create table if not exists case_history_identity_link (
  tenant_id varchar(120) not null,
  observation_id varchar(160) not null,
  identity_kind varchar(80) not null,
  identity_value varchar(600) not null,
  primary key (tenant_id, observation_id, identity_kind, identity_value),
  foreign key (tenant_id, observation_id)
    references case_history_observation (tenant_id, observation_id)
);

create table if not exists case_history_stream_cursor (
  tenant_id varchar(120) not null,
  source_stream varchar(200) not null,
  highest_sequence bigint not null,
  updated_at timestamp with time zone not null,
  primary key (tenant_id, source_stream)
);

create table if not exists case_history_collision (
  tenant_id varchar(120) not null,
  observation_id varchar(160) not null,
  original_sha256 char(64) not null,
  received_sha256 char(64) not null,
  recorded_at timestamp with time zone not null
);

create table if not exists replay_input_manifest (
  tenant_id varchar(120) not null,
  manifest_id varchar(160) not null,
  source_case_id varchar(160) not null,
  source_run_id varchar(160) not null,
  as_of_event_id varchar(240) not null,
  snapshot_ref varchar(600) not null,
  snapshot_sha256 char(64) not null,
  evidence_set_ref varchar(600) not null,
  evidence_set_sha256 char(64) not null,
  model_ref varchar(240),
  instruction_ref varchar(240) not null,
  tool_catalog_ref varchar(240) not null,
  policy_ref varchar(240) not null,
  configuration_ref varchar(240) not null,
  manifest_sha256 char(64) not null,
  retention_state varchar(40) not null,
  created_at timestamp with time zone not null,
  primary key (tenant_id, manifest_id)
);

create table if not exists replay_authorization (
  tenant_id varchar(120) not null,
  authorization_id varchar(160) not null,
  manifest_id varchar(160) not null,
  manifest_sha256 char(64) not null,
  replay_mode varchar(40) not null,
  purpose varchar(80) not null,
  actor_ref varchar(240) not null,
  policy_ref varchar(240) not null,
  issued_at timestamp with time zone not null,
  expires_at timestamp with time zone not null,
  authority_state varchar(40) not null,
  max_uses integer not null check (max_uses > 0),
  uses_consumed integer not null check (uses_consumed >= 0 and uses_consumed <= max_uses),
  effect_mode varchar(20) not null check (effect_mode = 'FORBIDDEN'),
  primary key (tenant_id, authorization_id),
  foreign key (tenant_id, manifest_id)
    references replay_input_manifest (tenant_id, manifest_id)
);

create table if not exists replay_execution (
  tenant_id varchar(120) not null,
  replay_id varchar(160) not null,
  replay_run_id varchar(160) not null,
  source_run_id varchar(160) not null,
  authorization_id varchar(160) not null,
  manifest_id varchar(160) not null,
  manifest_sha256 char(64) not null,
  replay_mode varchar(40) not null,
  purpose varchar(80) not null,
  execution_state varchar(40) not null,
  result_code varchar(40),
  result_sha256 char(64),
  result_gaps varchar(1000),
  request_sha256 char(64) not null,
  started_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  primary key (tenant_id, replay_id),
  foreign key (tenant_id, authorization_id)
    references replay_authorization (tenant_id, authorization_id),
  foreign key (tenant_id, manifest_id)
    references replay_input_manifest (tenant_id, manifest_id)
);
-- end::case-history-replay-schema[]
